import React from "react";

export default function ProjectPage(){
    return(
        <div className="relative min-h-screen text-white inset-0 h-full w-full items-center px-5 pb-24 pt-36 [background:radial-gradient(125%_125%_at_50%_10%,#000_40%,#63e_100%)]">
            <h1 className="text-4xl my-4 font-bold tracking-wider text-center">Experience</h1>
            <div className="my-4">
                <h1 className="text-2xl">GWUSEC</h1>
                <h2 className="text-xl">Privacy Labels Observatory: May 2023 - Present</h2>
                <ul className="list-disc ml-8">
                    <li>
                    Coordinated converting a research paper on Apple's privacy labels into an interactive website showcasing millions of applications into 4
                    corresponding privacy tags based on the level of privacy accessibility
                    </li>
                    <li>
                    Programmed a fullstack system, using a React.js frontend, a Django backend, and a SQL database, allowing users to view the expansive list of
                    applications and data analytics
                    </li>
                    <li>
                    Refactored the stack, after the transfer of the millions of applications across hundreds of runs to the non-relational database, to a React.js
                    frontend, a Node.js (Express) backend, and an Elastic database, for more efficient search performance
                    </li>
                    <li>
                    Initiated conversations with fellow researchers to conduct data analysis on millions of applications over the past four years
                    </li>
                </ul>
            </div>
            <div className="my-4">
                <h1 className="text-2xl">GW Systems Lab</h1>
                <h2 className="text-xl">Kernel Reductions: February 2024 - Present</h2>
                <ul className="list-disc ml-8">
                    <li>
                    Researched on reducing the size of the Kernel by more than half employing projects such as Essence and Cozart
                    </li>
                    <li>
                    Experimented with Python and open-source development and conducted traces of the Kernel in order to build relational mappings between
                    app configurations and corresponding Kernel calls
                    </li>
                    <li>
                    Utilized advanced testing tools such as QEMU tracer and ftrace to generate the mappings and rigorously verified the accuracy of the mappings
                    generated by Essence, ensuring seamless integration and optimal operation all four phases
                    </li>
                    <li>
                    Modified code-base by applying Github Actions to automate the Kernel reductions by more than half
                    </li>
                </ul>
            </div>
            <div className="my-4">
                <h1 className="text-2xl">GBCS</h1>
                <h2 className="text-xl">Fullstack Development: May 2024 - August 2024</h2>
            </div>
            <div className="my-4">
                <h1 className="text-2xl">GW</h1>
                <h2 className="text-xl">Student Academic Assistant: August 2023 - May 2024</h2>
            </div>
            <h1 className="text-4xl my-4 font-bold tracking-wider text-center">Projects</h1>

        </div>
    )
}